<?php
	class insert_model extends CI_Model
	{
		public function __construct()
		{
			parent::__construct();
			$this->load->database();
		}
		public function index()
		{
			$arr=array(
					'UId'=>'1191',
					'UName'=>'小墨',
					'UPw'=>md5('1191'),
					'power'=>'1'
				);
			$res=$this->db->insert('user',$arr);
			if($res)
				return true;
			else 
				return false; 
		}
		public function insert_sb(){
			$arr=array(
				'设备编号'=>$this->post->input('设备编号'),
				'分类号'=>$this->post->input('分类号'),
				'仪器名称'=>$this->post->input('仪器名称'),
				'型号'=>$this->post->input('型号'),
				'规格'=>$this->post->input('规格'),
				'单价'=>$this->post->input('单价'),
				'厂家'=>$this->post->input('厂家'),
				'出厂号'=>$this->post->input('出厂号'),
				'出厂日期'=>$this->post->input('出厂日期'),
				'购置日期'=>$this->post->input('购置日期'),
				'存放地名称'=>$this->post->input('存放地名称'),
				'经费科目名'=>$this->post->input('经费科目名'),
				'经费科目'=>$this->post->input('经费科目'),
				'使用方向'=>$this->post->input('使用方向'),
				'使用方向名'=>$this->post->input('使用方向名'),
				'领用人'=>$this->post->input('领用人'),
				'经手人'=>$this->post->input('经手人'),
				'记账人'=>$this->post->input('记账人'),
				'入库时间'=>$this->post->input('入库时间'),
				'资产类别'=>$this->post->input('资产类别'),
				'国际分类号'=>$this->post->input('国际分类号'),
				'国际分类名'=>$this->post->input('国际分类名'),
				'字符字段5'=>$this->post->input('字符字段5'),
				'国别码'=>$this->post->input('国别码'),
				'国别'=>$this->post->input('国别'),
				'输入日期'=>$this->post->input('输入日期'),
				'标志'=>$this->post->input('标志'),
				'变动日期'=>$this->post->input('变动日期'),
				'管理级别'=>$this->post->input('管理级别'),
				'使用单位号'=>$this->post->input('使用单位号'),
				'财务审核日期'=>$this->post->input('财务审核日期'),
				'初审日期'=>$this->post->input('初审日期'),
				'编号'=>$this->post->input('编号'),
				'数量'=>$this->post->input('数量'),
				'批量'=>$this->post->input('批量'),
				'财政分类id'=>$this->post->input('财政分类id'),
				'财政大类id'=>$this->post->input('财政大类id'),
				'申请原因'=>$this->post->input('申请原因'),
				'申请人'=>$this->post->input('申请人'),
				'申请日期'=>$this->post->input('申请日期'),
				'财政内主号'=>$this->post->input('财政内主号'),
				'领用单位号'=>$this->post->input('领用单位号'),
				'领用单位名'=>$this->post->input('领用单位名'),
				'现状名'=>$this->post->input('现状名'),
				'现状'=>$this->post->input('现状'),
				'设备来源'=>$this->post->input('设备来源'),
				'设备来源名'=>$this->post->input('设备来源名'),
				'采购形式名'=>$this->post->input('采购形式名'),
				'采购形式'=>$this->post->input('采购形式'),
				'备注'=>$this->post->input('备注'),
				'按十一类分'=>$this->post->input('按十一类分'),
				'按六类分'=>$this->post->input('按六类分'),
				'六类资产'=>$this->post->input('六类资产'),
				'财务凭单'=>$this->post->input('财务凭单'),
				'单据号'=>$this->post->input('单据号'),
				'科研号'=>$this->post->input('科研号'),
				'设备号'=>$this->post->input('设备号'),
				'字符字段1'=>$this->post->input('字符字段1'),
				'字符字段2'=>$this->post->input('字符字段2'),
				'字符字段3'=>$this->post->input('字符字段3'),
				'字符字段4'=>$this->post->input('字符字段4'),
				'数字字段1'=>$this->post->input('数字字段1'),
				'数字字段2'=>$this->post->input('数字字段2'),
				'数字字段3'=>$this->post->input('数字字段3'),
				'数字字段4'=>$this->post->input('数字字段4'),
				'图片文件'=>$this->post->input('图片文件'),
				'图文名称'=>$this->post->input('图文名称'),
				'图片文件1'=>$this->post->input('图片文件1'),
				'图文名称1'=>$this->post->input('图文名称1'),
				'附件数量'=>$this->post->input('附件数量'),
				'附件总价'=>$this->post->input('附件总价'),
				'审核'=>$this->post->input('审核'),
				'输入人'=>$this->post->input('输入人'),
				'清查方式'=>$this->post->input('清查方式'),
				'清查日期'=>$this->post->input('清查日期'),
				'清查异常'=>$this->post->input('清查异常'),
				'财务审核'=>$this->post->input('财务审核'),
				'财务审核人'=>$this->post->input('财务审核人'),
				'初审'=>$this->post->input('初审'),
				'初审人'=>$this->post->input('初审人'),
				'校区'=>$this->post->input('校区'),
				'存放地编号'=>$this->post->input('存放地编号'),
				'保修期限'=>$this->post->input('保修期限'),
				'折旧方式名'=>$this->post->input('折旧方式名'),
				'折旧方式'=>$this->post->input('折旧方式'),
				'处置方式'=>$this->post->input('处置方式'),
				'供货商'=>$this->post->input('供货商'),
				'价值类型'=>$this->post->input('价值类型'),
				'发票号'=>$this->post->input('发票号'),
				'申请负责人'=>$this->post->input('申请负责人'),
				'使用年限'=>$this->post->input('使用年限'),
				'累计折旧额'=>$this->post->input('累计折旧额'),
				'折旧残值'=>$this->post->input('折旧残值'),
				'净值'=>$this->post->input('净值'),
				'计量单位'=>$this->post->input('计量单位'),
				'变动领用人'=>$this->post->input('变动领用人'),
				'变动地名称'=>$this->post->input('变动地名称'),
				'变动地编号'=>$this->post->input('变动地编号'),
				'变动单据号'=>$this->post->input('变动单据号'),
				'财政资产号'=>$this->post->input('财政资产号'),
				'财审内头号'=>$this->post->input('财审内头号'),
				'财审资头号'=>$this->post->input('财审资头号'),
				'财审内体号'=>$this->post->input('财审内体号'),
                '财处内头号'=>$this->post->input('财处内头号'),
                '财处资头号'=>$this->post->input('财处资头号'),
                '财处内体号'=>$this->post->input('财处内体号'),
                '接收主管'=>$this->post->input('接收主管'),
                '收购单位'=>$this->post->input('收购单位'),
                '变人员编号'=>$this->post->input('变人员编号'),
                '人员编号'=>$this->post->input('人员编号'),
                '修改标志'=>$this->post->input('修改标志')
                		);
			$res=$this->db->insert('shebei',$arr);
			if($res)
				return true;
			else 
				return false;
		}
	}
?>